apiVersion: v1
kind: Namespace
metadata:
  name: cyberco
---
#namespaces should be created first before resources otherwise namespace doesn exist error will come

apiVersion: apps/v1
kind: Deployment

metadata:
  name: cache-db
  namespace: cyberco
  labels:
    app: cache-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cache-db
  template:
    metadata:
      labels:
        app: cache-db
    spec:
      containers:
      - name: cache-db
        image: redis:buster
        ports:
        - containerPort: 6379

---

# alias execute='kubectl apply -f filename' #sudo execute will not work
